# SITE CONFIGURATION
title: MATEUS BLOG # your site title
author: Mateus Toledo da Silveira Leão # You :P
description: > # Meta description of Homepage
  Conteúdo sobre ciência de dados, tomada de decisão em cenários complexos e otimização.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://mateustsleao.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Mateus Toledo da Silveira Leão
  links:
    - https://www.facebook.com/mateus.toledo0
    - https://www.linkedin.com/in/mateus-toledo-da-silveira-leao/
    - https://github.com/mateustsleao

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Publications', link: '/publications'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
  
tagline: >
  Meus estudos sobre ciência de dados, tomada de decisão em cenários complexos e otimização.

hero_img: posts/the-lesser-reef-nebula_1920x1200_blogdowallpaper.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: mateustsleao@gmail.com # email for form submission
formspree: xrgrryrz

github_username:  mateustsleao # replace with your_github_username or comment to remove link from footer
instagram_username: mateustolledo 
# linkedin_username: mateus-toledo-da-silveira-leao
disqus:
  shortname: mateustsleao # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag